apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dotnet-demoapp
  namespace: argo-events
spec:
  template:
    serviceAccountName: events-workflows-sa
  dependencies:
    - name: buildkit
      eventSourceName: dotnet-demoapp
      eventName: dotnet-demoapp-merge
  triggers:
    - template:
        conditions: buildkit
        name: dotnet-container-pipeline
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: dotnet-demoapp-
              spec:
                serviceAccountName: events-workflows-sa
                entrypoint: main
                arguments:
                  parameters:
                    - name: image
                    - name: branch
                    - name: path
                      value: build
                    - name: username
                    - name: repo
                volumeClaimTemplates:
                  - metadata:
                      name: work
                    spec:
                      accessModes: ["ReadWriteOnce"]
                      resources:
                        requests:
                          storage: 64Mi
                templates:
                  - name: main
                    steps:
                      - - name: call-extract-template
                          templateRef:
                            name: extract-git-token
                            template: extract
                          arguments:
                            parameters:
                              - name: secretName
                                value: github-access
                              - name: secretKey
                                value: token
                      - - name: call-clone-template
                          templateRef:
                            name: clone-git-repo
                            template: clone
                          arguments:
                            parameters:
                              - name: branch
                                value: "{{workflow.parameters.branch}}"
                              - name: username
                                value: "{{workflow.parameters.username}}"
                              - name: repo
                                value: "{{workflow.parameters.repo}}"
                              - name: token
                                value: "{{steps.call-extract-template.outputs.parameters.secretValue}}"
                      - - name: call-build-push-template
                          templateRef:
                            name: build-push-docker-image
                            template: build-push
                          arguments:
                            parameters:
                              - name: path
                                value: "{{workflow.parameters.path}}"
                              - name: image
                                value: "{{workflow.parameters.image}}"
          parameters:
           # workflow-name
            - src:
                dependencyName: buildkit
                dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}-{{ .Input.body.pull_request.title }}"
              dest: metadata.name
              operation: append
            # image-tag
            - src:
                dependencyName: buildkit
                dataTemplate: "nethopper/dotnet-demoapp:{{ .Input.body.pull_request.title }}"
              dest: spec.arguments.parameters.0.value
            # branch
            - src:
                dependencyName: buildkit
                dataKey: body.pull_request.base.ref
              dest: spec.arguments.parameters.1.value
            # git-username
            - src:
                dependencyName: buildkit
                dataKey: body.pull_request.user.login
              dest: spec.arguments.parameters.3.value
            # repo-name
            - src:
                dependencyName: buildkit
                dataKey: body.pull_request.base.repo.full_name
              dest: spec.arguments.parameters.4.value
      retryStrategy:
        steps: 3
