apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-09-17T10:07:43+02:00'
    nethopper.io/generator-version: unknown
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    creds: >-
      AgBMckqylckidu2O4YqGzlnG9DcHC5x/dI7IoqtsMpYdAPGgi5ZTAPVoqCP9FkalP3sHvbhAJVJDICU1ldU7SEzHWJ+AeGw15wsFrC2YtgtnogugxHgc8mfGFWLmSGANRtK5rTFGQKEkGOeL2HEqbfXJaU7A8pG+NbheH7H8LexCN9wNSOcPa/ncED3alWwiafO9nj5/DMOzIR3EiHBMH14cDOrt+xX5sOIifxtvE1/Nn033LJ90KbH+yR+wX5TLxsBMKaqyfxC2QeeiLs8OhVsX4o3m2NJsN9qmVYEbjoO1+78fJp6BakTaCXD92Ve4tT0HB8rFVkOouVeGItn2E4QhdUTyn92f2JASbFPxR03AOFtcauH+FDHPq7ioEZcU9AsqOmr0lopTEdeZLI4TM+zeyz8G5TYKEVJHqHn5XbwTPsEory3yvqjqz+uKSyKtgTasi/UfvPVZSfevjjq/V8ecaWwJSslsiaTFG35sA//a/M3Zh12YNiE6XV3CuIEnzOmi+4x16jDz7rvkTaWVICGSFJ+l2771qFUqtAd3XOOMVwz/H9ysyWyIYAJsRpefP3zSGh7wMlBEyRh7LEB4LvofDcvsFf037jjDTUT5eQiDCSziPR+ka34GVQn+6U73lNc58aFeDHFITdos/WSyOQSKL0AExDDB9kSA5cDyoJj/MkqvdNLAD1b4ZuLBUer6ST72TspeBMpYk1ryIjkYjVN8Mn5R3deY1KcqFIZJJMDVGr8kFcMIGEhg4B3ZtvdIi/nIDXIfgz6vKtrGrN+2IsBaGWwrGE+V9s5AwLpR1z/U+JUw1ZOtbLPBVVAX/2hTi9jLm4uvL34IRmrvAapvw74n3aDz5Dc2YedIzv0=
  template:
    metadata:
      annotations: *ref_0
      name: aws-secret
    type: Opaque
