apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-08-26T08:58:55+02:00'
    nethopper.io/generator-version: v6.0.0-3bbb8a5ee2
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    creds: >-
      AgBBBMEH4G1mcWVztpfAi3lHtD5haLPlyIPIUtM6CmusCQGdcVtuZWkiYmtHD+6E/VX0smACwuKz2GPDEGdLx+fFVlOMyEztMYVGJ4HyRwor4PjygYWykV652nJqClw6OmXW6WYWP7NmsabOgP70VqnJ8KcBWDhoycaY2Lq6UoZuqAafwu+vzl6GPeP/mzqCf8nAtokH4arvbtRJHi9liAU9vdpoEZpDFkoxoF85yMm8tYaTt6zt5rqk+s8g0JzluPuemOFTnPJi7safty3euUKnm21ea5i2SQpuHeAvZJbQ/Neg7i1y5VkmHJ9aEHj1DnLnt4OoI84vOF6ESvxI3PxF7q96f1vJeKUMiXlf+xpHTzkIKy7F1rE2CSBtJ9+6Gf3UaCs3icq8JuiY//TgscuYUil3TwfroVmqZOg6X/UZrTt/9uDICnEn9DeYkbv0fZxlYDxW3lKKknobQN7U5cDbp6kSDm+ZnhHYDoM0DI3aEl3jplxLAdqvNLM7VwXR9ES+5d+JzMy5eygZurrk8FiwE1wPDD6126DueZheiVsP/lKV4V+W4GY2NjkKbEWOk0GTIQ2XtDcgx2cBY06PD6w9/Seu2N/n9i9fHfiXdCofme12J+2vkhEc+O40NtR9fzb0mRrnLl2Rn2zsnOlzvYOHu3iMzo10mh8k8P6fLoV4YLKuvvlBkcs4Pi6xNuL2VKzEAipa3wmWjlgXjQciu24GQiNDzzB/6ksGv33LQs5uH+CjN86idEvjsqnYr7jEjFzMyRiFiZuJJ6sfSp92uT8D8wexZANscnqgAi37eDm7ox/oSZaG9UTFmpyHd6jFqZycQz73euaRVL2A5wkfl/k7yDZ/vVEJLYM6kpA=
  template:
    metadata:
      annotations: *ref_0
      name: aws-secret
    type: Opaque
