apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-09-26T10:58:01+02:00'
    nethopper.io/generator-version: v1.0.1-89e0fd0682
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    creds: >-
      AgBQ+M8WRWD3DUdvv98HUer4sD3aBp/QnEivLWZRM3ainNQBMQ8i8pZBKyTklA+mjZ6CCeiGFiNFV4cOZDlu72pceuRF2GMSUkZgRBufnGQCeaiX+eUgiC5aoF4ClvSWgMyyjaY3OCFZoNapgql2akQqEvWvHCQOBSTdqXo6oFnBlHboE68vbpuJZYL58pvO1W+5g6pVy1y96MGw1QiJNZmrevH4Rpakhikj7c1r8LasmHtZ4wTM+s2BhwVD4qlIvbPeChL8mAQXAgKl4IoIZOE4WsoQmthURDHB8RjKllbv+nYD8coli2rfF92/wDyQvmofXzQgccsoVXFxlbSPNOAgByroDPIwqWubeiCb3Jw/1P6d0ZKuCKzMjWh0tfI5Qrnge+qBa55tg6If+Lr2ZqkRsUFT9ooSDTN7PDv5rTqrnJB41Umt/PkbwVnHvPRXaKTa0eNSWsXoJaQEiRKiHrNx3otaqFQZuZ261OCxGxmu+HqyLxVwx+4ffZhXO7d51wjExxyIM+XppC1svKbfrA4EXaEyE2eReaGsOaUY8Ka/iIafay45XKahFJa42bds21AHk8q+G0wT7TAFpTSYALMgWfP0r0EobTRWwpSt86RZvXM4j2agHdpxCGStCZSOznyzn2bfW/RKYd6DTb94LI8pdzxmnDAkj3mD9JY0HMyvcrx5QtCE/eHgPT3dSwa5/yMRfQtUYhhRwb+jreTo8e2WH1IK2qlALIlBWyu6P03xNcZlt06H5y9Mj4UqQxt5iPswjwi0W51tHw8NFukWxyFoX67768MDBO/RMcfWN0dHdoblSXXyY2DxVA18nsw0/KxJa44c+5PFhQotS9vwnNUl0wFWZNi4b2U5nRo=
  template:
    metadata:
      annotations: *ref_0
      name: aws-secret
    type: Opaque
