apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: eks-125
  namespace: nethopper
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/aws/eks-aws
    vars:
    - key: region
      value: us-west-2
    - key: cluster-name-suffix
      value: eks-125
    - key: k8s-version
      value: "1.25"
  writeConnectionSecretToRef:
    namespace: default 
    name: eks-125
  providerConfigRef:
    name: awsconfig
