apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: cloudflow-eks-dev
  namespace: nethopper 
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/aws/eks-aws
    vars:
    - key: region
      value: us-west-2
    - key: cluster-name-suffix
      value: eks-dev-2 
  writeConnectionSecretToRef:
    namespace: default
    name: cloudflow-eks-dev
  providerConfigRef:
    name: tfconfig
