apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: cloudflow-eks-prod
  namespace: nethopper
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/aws/eks-aws
    vars:
    - key: region
      value: us-west-1
    - key: cluster-name-suffix
      value: eks-prod 
  writeConnectionSecretToRef:
    namespace: default 
    name: cloudflow-eks-prod
  providerConfigRef:
    name: tfconfig
